AssetsMap: 
    Values: 
        settings-key: LykkePay-AssetsMap-Values
        types: [Json, Tag]
    InvoiceCreationPairs: 
        settings-key: LykkePay-AssetsMap-InvoiceCreationPairs
        types: [Json, Tag]

AssetsServiceClient: 
    ServiceUrl: 
        settings-key: AssetsServiceUrl
        types: [Tag]
    ExpirationPeriod: 
        settings-key: AssetsServiceExpirationPeriod
        types: [Tag]

BalancesServiceClient: 
    ServiceUrl: 
        settings-key: BalancesServiceUrl
        types: [Tag]

EmailPartnerRouterServiceClient: 
    ServiceUrl: 
        settings-key: EmailPartnerRouterServiceUrl
        types: [Tag]

MonitoringServiceClient: 
    MonitoringServiceUrl: 
        settings-key: MonitoringServiceUrl
        types: [Tag]

PayAuthServiceClient: 
    ServiceUrl: 
        settings-key: PayAuthServiceUrl
        types: [Tag]

PayInternalServiceClient: 
    ServiceUrl: 
        settings-key: PayInternalServiceUrl
        types: [Tag]
  
PayInvoicePortal: 
    EnableSignup: 
        settings-key: PayInvoicePortal-EnableSignup
        types: [Tag, Optional]
    BlockchainExplorerUrl: 
        settings-key: PayInvoicePortal-BlockchainExplorerUrl
        types: [Tag]
    EthereumBlockchainExplorerUrl: 
        settings-key: LykkePayEthereumBlockchainExplorerUrl
        types: [Tag]
    PortalTestnetUrl:
        settings-key: PayInvoicePortal-PortalTestnetUrl
        types: [Tag,Optional]
    ApiaryDocsDomain: 
        settings-key: PayInvoicePortal-ApiaryDocsDomain
        types: [Tag]
    UserLoginTime: 
        settings-key: PayInvoicePortal-UserLoginTime
        types: [Tag]
    AssetsCacheExpirationPeriod: 
        settings-key: PayInvoicePortal-AssetsCacheExpirationPeriod
        types: [Tag]
    CacheExpirationPeriods: 
        BaseAsset: 
            settings-key: PayInvoicePortal-CacheExpirationPeriods-BaseAsset
            types: [Tag]
        Rate: 
            settings-key: PayInvoicePortal-CacheExpirationPeriods-Rate
            types: [Tag]
        MerchantName: 
            settings-key: PayInvoicePortal-CacheExpirationPeriods-MerchantName
            types: [Tag]
    Db:
        SubscriptionConnectionString: 
            settings-key: LykkePayDataConnString
            types: [AzureTableStorage, Tag]
        LogsConnectionString: 
            settings-key: LykkePayLogsConnString
            types: [AzureTableStorage, Tag]

PayInvoiceServiceClient: 
    ServiceUrl: 
        settings-key: PayInvoiceServiceUrl
        types: [Tag]
  
RateCalculatorServiceClient: 
    ServiceUrl: 
        settings-key: RateCalculatorServiceUrl
        types: [Tag]
  
SlackNotifications: 
    AzureQueue: 
        ConnectionString: 
            settings-key: SlackNotificationsConnString
            types: [AzureTableStorage]
        QueueName: slack-notifications
    ThrottlingLimitSeconds: 
        settings-key: SlackNotificationsThrottlingLimit

PayMerchantServiceClient:
    ServiceUrl:
        settings-key: PayMerchantServiceUrl
        types: [Tag]
  